name: Create tag and release

on:
  push:
    branches:
      - main

jobs:
  check-commit:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check.outputs.result }}
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Check commit message
        id: check
        run: echo "result=$(echo '${{ github.event.head_commit.message }}' | grep -o 'v[0-9.]\+$')" >> $GITHUB_OUTPUT
        shell: bash
      - name: Get version
        id: get-version
        run: echo "version=$(echo '${{ github.event.head_commit.message }}' | grep -o 'v[0-9.]\+$')" >> $GITHUB_OUTPUT
        shell: bash
  create-release:
    runs-on: ubuntu-latest
    needs: ["check-commit"]
    if: ${{ needs.check-commit.outputs.result != '' }}
    steps:
      - name: 버전 정보 추출
        run: echo "##[set-output name=version;]$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
        id: extract_version_name
      - name: Release 생성
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version_name.outputs.version }}
          release_name: ${{ steps.extract_version_name.outputs.version }}
  trigger-deploy:
    runs-on: ubuntu-latest
    needs: ["create-release"]
    name: Trigger publish workflow
    steps:
      - uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'npm-publish.yml',
              ref: 'master',
            })
