name: Create tag and release

on:
  push:
    branches:
      - main

jobs:
  check-commit:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check.outputs.result }}
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Check commit message
        id: check
        run: echo "result=$(echo '${{ github.event.head_commit.message }}' | grep -o 'v[0-9.]\+$')" >> $GITHUB_OUTPUT
        shell: bash
      - name: Get version
        id: get-version
        run: echo "version=$(echo '${{ github.event.head_commit.message }}' | grep -o 'v[0-9.]\+$')" >> $GITHUB_OUTPUT
        shell: bash
  check-tag:
    runs-on: ubuntu-latest
    needs: ["check-commit"]
    if: ${{ needs.check-commit.outputs.result != '' }}
    steps:
      - uses: actions/checkout@v3
      - name: Check Tag
        id: tag
        run: |
          ${{  github.ref_name }}"

  create-release:
    runs-on: ubuntu-latest
    needs: ["check-commit", "check-tag"]
    if: ${{ needs.check-tag.outputs.tag-exists == 'false' }}
    steps:
      - uses: actions/checkout@v3
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.check-commit.outputs.version }}
          name: ${{ needs.check-commit.outputs.version }}
          body: ${{ needs.check-tag.outputs.release-body }}
  trigger-deploy:
    runs-on: ubuntu-latest
    needs: ["create-release"]
    name: Trigger publish workflow
    steps:
      - uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'npm-publish.yml',
              ref: 'master',
            })
